micronaut:
  application:
    name: ia03-be

  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
    intercept-url-map:
      - pattern: /swagger/**
        access: isAnonymous()
      - pattern: /swagger-ui/**
        access: isAnonymous()
    cors:
      enabled: true
      configurations:
        web:
          allowedMethods:
            - GET
            - OPTIONS
            - POST
            - PUT
            - DELETE
            - PATCH
          allowedOrigins:
            - ${ALLOWED_ORIGIN:}
            - ^http:\/\/localhost(:[0-9]+)?$
            - ^http:\/\/([\w-]+\.)*localhost(:[0-9]+)?$
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    db-type: postgres
    driver-class-name: org.postgresql.Driver

app:
  database:
    url: ${DB_URL:localhost}
    name: ${DB_NAME:local}
    username: ${DB_USERNAME:local}
    password: ${DB_PASSWORD:local}
    port: ${DB_PORT:5432}

flyway:
  datasources:
    default:
      enabled: true